### ISSUE TITLE
The return value of 'sscanf()' should be checked

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [IBM/scheduler-library#1]
1.
https://github.com/IBM/scheduler-library/blob/1b96e932f5d142e18b36e6e90b79d4379a35d010/src/read_trace.c#L56

2. 
https://github.com/IBM/scheduler-library/blob/1b96e932f5d142e18b36e6e90b79d4379a35d010/src/read_trace.c#L78

**Comment by jdwellman** [comment]
Addressed in commit https://github.com/IBM/scheduler-library/commit/7d6ceae1ae191543732ecfe3b6cbedda6bb67220
