### ISSUE TITLE
Stream pointer might be NULL

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [IBM/scheduler-library#2]
'fp' is defined here, but may be NULL
https://github.com/IBM/scheduler-library/blob/7e25215e995272b38376ffdcc8f9a6a18b8dd2df/src/octave.c#L6
Stream pointer might be NULL
https://github.com/IBM/scheduler-library/blob/7e25215e995272b38376ffdcc8f9a6a18b8dd2df/src/octave.c#L9

**Comment by jdwellman** [comment]
Addressed in the commit:
https://github.com/IBM/scheduler-library/commit/e9797b64cb6d266172d53b0a20566c8f88ab0db9
by taking in the associated changes from the original Mini-ERA repository.
